# .github/workflows/cli-check.yml
name: Lint & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install typer[all] jinja2 loguru questionary rich

      - name: Lint
        run: |
          pip install flake8
          flake8 fluttercraft

      - name: Run CLI help
        run: |
          python -m fluttercraft --help
