# .github/workflows/cli-check.yml
name: Lint & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install typer[all] pyfiglet colorama rich prompt_toolkit pygments
          pip install -e .

      - name: Lint with flake8
        run: |
          pip install flake8
          # Use .flake8 config file for linting rules
          flake8 fluttercraft

      - name: Run CLI help
        run: |
          fluttercraft --help

      - name: Test version flag
        run: |
          fluttercraft --version || echo "Version flag not implemented yet 🥲"
