# .github/workflows/cli-check.yml
name: Lint & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install typer[all] pyfiglet colorama rich
          pip install -e .

      - name: Lint
        run: |
          pip install flake8
          flake8 fluttercraft

      - name: Run CLI help
        run: |
          fluttercraft --help

      - name: Test version flag
        run: |
          fluttercraft --version || echo "Version flag not implemented yet."
